# Generated by Django 5.2.5 on 2025-08-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactinfo_footerlink_hero_message_navbarlink_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='skills',
            new_name='skills1',
        ),
        migrations.AddField(
            model_name='project',
            name='skills2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skills3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skills4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
